### ISSUE TITLE
Create upgrade script and doc for utf8mb4 migration 

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Asqatasun#256]
## Observed behaviour

An existent instance of Asqatasun v4.0.3 needs a script  and documentation on how to update since #123 has landed in `develop` branch

## Expected behaviour

Provide : 

* an automated update script
* documentation on how to manually upgrade

## Tasks

Upgrade script:

- [x] SQL: test script on a plain install (Ubuntu 14.04, Mysql 5.5.62), with an empty DB 
- [x] SQL: test script on a plain install (Ubuntu 14.04, Mysql 5.5.62), with DB filled with production data (2 different sets)
- [x] SQL: double check from the git log history that each table / field modified to utf8mb4 is actually "converted to" by the script. Put differently: do not forget anything.
- [x] verify modification of `asqatasun.conf`
- [x] delete + recreate procedures

Documentation UPGRADE doc:

- [x] explain SQL commands needed

Documentation CHANGELOG:

- [x] add changes
- [x] add entry in section "upgrade-o-meter"
